### ISSUE TITLE
Required block in clients

### ISSUE THREAD

**Issue by WeArePercipio** [percipioglobal/percipio-site#452]
content blocks are required in the clients entry type when none are really needed
<img width="1193" alt="Screenshot 2022-06-17 at 11 54 11" src="https://user-images.githubusercontent.com/1466061/174285485-7eea40d2-d4c1-4783-99ec-102eff4e1f69.png">

**Comment by cookie10codes** [comment]
@CraigClement go to the content builder field and change the min blocks from 1 to 0
